<?php include("blocks/head.php"); ?>
<?php include("blocks/header.php"); ?>
<?php include("blocks/quicklinks.php"); ?>
<?php include("blocks/home.php"); ?>
<?php include("blocks/challenge.php"); ?>
<?php include("blocks/approach.php"); ?>
<?php include("blocks/offerings.php"); ?>
<?php include("blocks/impact.php"); ?>
<?php include("blocks/join.php"); ?>
<?php include("blocks/footer.php"); ?>